fixies
NikitaLi/ImageMover pull request #2
Opened 2017-07-17 21:46 UTC by NikitaLipatov

2017-07-18 12:57 UTC, essiorh requested changes

2017-07-18 12:57 UTC, essiorh commented on app/src/main/java/com/example/sony/imagemover/Activity2.java
> +        Button mBtnStop = (Button) findViewById(R.id.stop_button);
Название переменной

2017-07-18 12:57 UTC, essiorh commented on app/src/main/java/com/example/sony/imagemover/Activity2.java
> +        ImgFragment currentFragment = (ImgFragment) fragmentManager.findFragmentByTag(Integer.toString(currentFragmentId));
Превышение 100 символов

2017-07-18 12:57 UTC, essiorh commented on app/src/main/java/com/example/sony/imagemover/Activity2.java
> +                    ImgFragment fragment = (ImgFragment) fragmentManager.findFragmentByTag(Integer.toString(j));
Превышение 100 символов

2017-07-18 12:57 UTC, essiorh commented on app/src/main/java/com/example/sony/imagemover/Activity2.java
> +            fragment.setListener(this);
Получение ссылки на активити во фрагментах лучше всего реализовывать через метод onAttach и чистить ссылку на методе onDetach

2017-07-18 13:06 UTC, essiorh commented on app/src/main/java/com/example/sony/imagemover/ImgFragment.java
>          else {
по кодстайлу нужно оставлять на той же строке, где и скобка

2017-10-31 23:10 UTC, NikitaLi approved these changes

2017-10-31 23:11 UTC, merged